### ISSUE TITLE
Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by aljrico** [tidyverse/googlesheets4#84] opened 2020-01-03 15:37 UTC
Following [this article](https://googlesheets4.tidyverse.org/articles/articles/drive-and-sheets.html) I've tried to log in to my google drive account, so I can set up an app to handle files in my drive account.

I follow this instructions as:

```
library(googledrive)
library(googlesheets4)
```

And then 

```
drive_auth()
sheets_auth(token = drive_token())
```

When executing `drive_auth()`, the explorer pops open with the following error message:

![image](https://user-images.githubusercontent.com/18146781/71732356-f286ec00-2e3e-11ea-81a1-f0e23ba80f5d.png)

> 
> Error: redirect_uri_mismatch
> 
> The redirect URI in the request, http://localhost:1410/, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/251575276543-m3emm4p2f5c530v183ddgmldget197d5.apps.googleusercontent.com?project=251575276543

**Comment by jennybc** [comment] 2020-01-03 19:53
> so I can set up an app to handle files in my drive account.

In what sense are you using the word "app" here? Because I understand it as referring to an OAuth app  (a client id and secret). Have you configured your own OAuth app?

**Comment by jennybc** [comment] 2020-01-03 20:58
Also, what versions of these packages do you have installed? Use `packageVersion("googledrive")` and `packageVersion("googlesheets4")` to produce this.

**Comment by aljrico** [comment] 2020-01-05 10:24
Hi! I'm trying to build a shiny app, but I figure it'd only be an example.

```
packageVersion('googlesheets4')
[1] ‘0.1.0.9000’

packageVersion('googledrive')
[1] ‘1.0.0.9000’
```

**Comment by jennybc** [comment] 2020-01-06 07:44
gargle, and therefore googlesheets4, doesn't have a smooth token flow for a Shiny app -- in the sense of obtaining and managing a token on behalf of the user. Without more detail -- specifically, code with exactly what you're trying to do -- I'm going to guess that you are probably trying to do something that is quite hard right now. Within in a Shiny app, current googlesheets4 can easily use a built-in token (or no token at all) . I'm going to close this because I believe this is tracked by https://github.com/r-lib/gargle/issues/14. If I've misunderstood, please point to some code so I can have more information.

**Comment by aljrico** [comment] 2020-01-06 11:43
Maybe I mislead the issue by explaining too much of the context in which I was using it. The main problem is that simply running 

```
library(googledrive)
library(googlesheets4)

drive_auth()
```

Immediately opens 
![image](https://user-images.githubusercontent.com/18146781/71816130-893eed00-3079-11ea-812a-f0c3131f0266.png)

With an error

**Comment by jennybc** [comment] 2020-01-06 17:14
I cannot reproduce this. I see:

```
> library(googledrive)
> library(googlesheets4)
> drive_auth()
The googledrive package is requesting access to your Google account. Select a pre-authorised account or enter '0' to obtain a new token. Press Esc/Ctrl + C to abort.

1: PERSON_1@gmail.com
2: PERSON_2@gmail.com
3: PERSON_3@rstudio.com

Selection: 3
```

So I think there must be more going on.

Back to my first question:

> In what sense are you using the word "app" here? Because I understand it as referring to an OAuth app (a client id and secret). **Have you configured your own OAuth app?**

Is there any other possibly relevant context about where you are executing this code? It certainly seems like something is setup incorrectly with the OAuth app. But if you are using the default app, it should "just work". If something was wrong with the default app, no one would be able to use google drive or googlesheets4 or bigrquery, but that is not the case.

**Comment by jennybc** [comment] 2020-01-06 17:19
The GCP project in the screenshotted error message does *not* match the one used by the tidyverse. So that strongly suggests you (or someone who can influence your R startup) has set up an OAuth app and that it is misconfigured.

**Comment by aljrico** [comment] 2020-01-10 09:22
To reproduce my error, the selection should be 0.  Because the intent is to obtain a new token

**Comment by jennybc** [comment] 2020-01-10 20:28
I can also get new tokens by selecting 0.

I really think this is an important point that has to be resolved:

> The GCP project in the screenshotted error message does not match the one used by the tidyverse. So that strongly suggests you (or someone who can influence your R startup) has set up an OAuth app and that it is misconfigured.

You are getting an error about redirect_uri_mismatch and the redirect URI is part of the OAuth app. And AFAICT you are using a custom OAuth app, not the one that ships with googlesheets4/gargle.

**Comment by jennybc** [comment] 2020-02-22 17:25
Closing for lack of activity / necessary details.

**Closed by jennybc** 2020-02-22 17:25 UTC
