### ISSUE TITLE
Write a sheet to a specific sub-folder

### ISSUE THREAD

**Issue by seanchrismurphy** [tidyverse/googlesheets4#131] opened 2020-03-18 23:20 UTC
I know this was requested under the old version of googlesheets and wasn't really possible, but was wondering if it's possible to now add the possibility of writing sheets to sub folders? 

e.g. I would expect

```r
googlesheets4::sheets_create(name = 'Folder/subfolder/data', sheets = dat)
```

To create a worksheet called data in the Folder/subfolder directory. Instead it just created a sheet named 'Folder/subfolder/data' in the global directory.

**Comment by jennybc** [comment] 2020-03-19 16:19
Duplicate of #111, which explains a few solutions.

**Closed by jennybc** 2020-03-19 16:19 UTC
