### ISSUE TITLE
Special characters when reading. 

### ISSUE THREAD

**Issue by grwhumphries** [tidyverse/googlesheets4#150] opened 2020-04-25 12:41 UTC
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

At the moment, special characters are not being read correctly (or encoded correctly?).  For example:   "Militão", when reading a spreadsheet (where it display as such in the spreadsheet), will get printed as "MilitÃ£o".   

I suppose it's probably not been implemented yet, but would be very helpful for non-english languages that use a lot of accents or special characters. 

```r
# insert reprex here
```

**Comment by jennybc** [comment] 2020-04-25 18:24
Duplicate of #26, #47, #56, and #121. The fix is to install the dev version of gargle, which I hope to submit to CRAN next week (and the googlesheets4 can go).

**Closed by jennybc** 2020-04-25 18:24 UTC
