### ISSUE TITLE
Possible feature: specify column type of last resort (e.g. 'character' instead of 'list')

### ISSUE THREAD

**Issue by Flavjack** [tidyverse/googlesheets4#64] opened 2019-11-23 11:14 UTC
For example in a table with a column with numbers and strings the column is recognized as a list

![image](https://user-images.githubusercontent.com/7735493/69477669-3a9b0380-0de9-11ea-9d06-897142aa9be0.png)
![image](https://user-images.githubusercontent.com/7735493/69477765-9914b180-0dea-11ea-9282-aa6655a9297d.png)

So, when is imported to R the missing values is treated as NULL value
 
![image](https://user-images.githubusercontent.com/7735493/69477695-8e0d5180-0de9-11ea-961c-0a80b4c3fb42.png)

And when i use the "`r options(knitr.kable.NA = '')`" the result is the following

![image](https://user-images.githubusercontent.com/7735493/69477712-d7f63780-0de9-11ea-87b2-260558d6f48f.png)

Usually in a column with number and string the column is treated as character but in this case is treated as a list. There is any reason for transformation or i should proceed in different way?

many thanks for develop this fantastic package!!

**Comment by m-macaskill** [comment] 2019-12-04 03:18
Am finding similar issues. Looks like this is similar to what was reported in #18, replied to by @jennybc as under consideration as part of #51.

**Comment by jennybc** [comment] 2019-12-04 13:56
This is working as designed/intended and documented.

The default column type, when unspecified is "guess":

> A type is guessed for each cell and then a consensus type is selected for the column. If no atomic type is suitable for all cells, a list-column is created, in which each cell is converted to an R object of "best" type". If no column types are specified, i.e. `col_types = NULL`, all types are guessed.

So, if a column contains a mix of string and numeric data (and, you could easily imagine, date-times), we read each cell as we find it and discover its "native" type in the spreadsheet. Then, in order to combine them into data frame column, we must make a list-column in this case (mixed types). This avoids a lossy coercion.

This is consistent with where the underpinnings of the tidyverse are heading re: vector handling, best manifested in the [vctrs package](https://vctrs.r-lib.org). Specifically see [Coercing to common type](https://vctrs.r-lib.org/articles/type-size.html#coercing-to-common-type).

> The common type of atomic vectors is computed very similar to the rules of base R, except that we do not coerce to character automatically.

According to the vctrs, there is no common type for character and numeric:

``` r
vctrs::vec_ptype_common(4, "d")
#> Error: No common type for `..1` <double> and `..2` <character>.
```

If you want a column to be character, even if it contains numeric and date cells, you need to specify that via `col_types`, e.g. `col_types = "c"` or `col_types = "cnclD?".

Alternatively, you can coerce to character after import, on the R side, perhaps after you've explored the data and confirmed you really want to coerce numbers to strings.

I feel like this is the **right** thing to do. But I can see that there will be sheets where it feels like it's making extra work. So I will have a think on ways for a user to express a wish to "never make list-columns" or to regard "character" as the cell / column type of last resort.

**Comment by m-macaskill** [comment] 2019-12-04 22:16
I agree that using lists in this situation is the most correct thing to do, in terms of not accidentally squashing data values, although in many, many cases, the user would probably be happy with a character column, and so providing that option would be realy useful.

However, an additional difficulty here is the context in which needing to change the column types occurs, especially for very wide spreadsheets. In `googlesheets` there is much more flexibility than is (currently) available in `googlsheets4`. This is compounded because columns containing lists can break the display of data frames in the RStudio environment pane (meaning that the displayed list of variables can be truncated). This makes it harder to inspect a data frame after an import and check which (of possibly very many) columns have correct or incorrect data types: it becomes an iterative process of importing the data and flattening any list columns, in order to be able to see the remainder. 

That iterative process occurs while also trying to maintain a potentially very long string of format characters and manipulate each until the appropriate result is achieved. With `googlesheets`, one could just specify types for individual columns by name, to use if a particular guess was incorrect. e.g. for some sheet with one errant column type, `googlesheets` code would look like this:

```
col_types = readr::cols(height_m = readr::col_number())
```

vs, say this in `googlesheets4`:

```
 col_types = 'cccDDcccccccccncccccccccccccccccccnnnnnnnnnnnnnncccccccccc') %>%
```
just to enforce the type of one column. Although I guess we could use `?` for all columns but one, counting characters to specify exactly the right one is tricky.

So I guess while I agree that the provision of list columns is potentially very valuable, they would be much less painful to use if `googlesheets4` retained the ability to set column types individually, rather than on an all-or-nothing basis.

**Comment by jennybc** [comment] 2019-12-04 23:48
The need for a more flexible column type is interface is already covered in #51

**Comment by jennybc** [comment] 2021-03-08 23:40
I consider this as part of #51, so closing this.

**Closed by jennybc** 2021-03-08 23:40 UTC
Labels: types :factory:
